/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.coursework_2;

/**
 *
 * @author w1784229
 */
public class Signup_Page extends javax.swing.JFrame {

    /**
     * Creates new form Signup_Page
     */
    public Signup_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passTxt = new javax.swing.JTextField();
        userTxt = new javax.swing.JTextField();
        userLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        CreateLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        SignupBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 332, 227, -1));

        userTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });
        getContentPane().add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 293, 227, -1));

        userLbl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        userLbl.setText("Username:");
        getContentPane().add(userLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 296, -1, -1));

        passwordLbl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        passwordLbl.setText("Password:");
        getContentPane().add(passwordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 335, -1, -1));

        emailLbl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        emailLbl.setText("Email Address:");
        getContentPane().add(emailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 374, -1, -1));

        EmailField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(EmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 371, 227, -1));

        CreateLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        CreateLbl.setText("Create an account");
        getContentPane().add(CreateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 73, -1, -1));

        backBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 571, 89, -1));

        SignupBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        SignupBtn.setText("Signup");
        SignupBtn.setPreferredSize(new java.awt.Dimension(73, 31));
        SignupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SignupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 571, 89, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-570, 0, 1070, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.toBack();
        setVisible(false);// TODO add your handling code here:
        new Login_Page().toFront();
        new Login_Page().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_backBtnActionPerformed

    private void SignupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignupBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CreateLbl;
    private javax.swing.JTextField EmailField;
    private javax.swing.JButton SignupBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField passTxt;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JLabel userLbl;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
