/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.coursework_2;

import javax.swing.JOptionPane;

/**
 *
 * @author w1784229
 */
public class Login_Page extends javax.swing.JFrame {
    
    /**
     * Creates new form Login_Page
     */
    public Login_Page()  {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordLbl = new javax.swing.JLabel();
        userLbl = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JTextField();
        LoginBtn = new javax.swing.JButton();
        QuitBtn = new javax.swing.JButton();
        WelcomeLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordLbl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        passwordLbl.setText("Password:");
        getContentPane().add(passwordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 313, -1, -1));

        userLbl.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        userLbl.setText("Username:");
        getContentPane().add(userLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 274, -1, -1));

        userTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });
        getContentPane().add(userTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 271, 227, -1));

        passwordTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 310, 227, -1));

        LoginBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LoginBtn.setText("Login");
        LoginBtn.setPreferredSize(new java.awt.Dimension(90, 31));
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 532, -1, -1));

        QuitBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        QuitBtn.setText("Exit");
        QuitBtn.setPreferredSize(new java.awt.Dimension(90, 31));
        QuitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(QuitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 532, -1, -1));

        WelcomeLbl.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        WelcomeLbl.setText("Welcome to our Lanuage app");
        getContentPane().add(WelcomeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 49, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Please enter your details to login");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 239, -1, -1));

        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setText("Signup");
        jButton2.setPreferredSize(new java.awt.Dimension(71, 31));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 532, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\w1784229\\Pictures\\d443331f98d9d762469790e530a70567.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-560, -50, 1060, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitBtnActionPerformed
        System.exit(0);        
    // TODO add your handling code here:
    }//GEN-LAST:event_QuitBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.toBack();
        Signup_Page sign = new Signup_Page();
        sign.setVisible(true);
        sign.toFront();        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        this.toBack();
        MainMenu_LanguageLevel main = new MainMenu_LanguageLevel();
        main.setVisible(true);
        main.toFront();
        JOptionPane.showMessageDialog(main,"Succefully logged in");  
    }//GEN-LAST:event_LoginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton QuitBtn;
    private javax.swing.JLabel WelcomeLbl;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JLabel userLbl;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
